env:
  matrix:
    - SCHEME="ChezScheme_master"
    # - SCHEME="Guile_2.0"
    - SCHEME="Guile_2.2"
    # - SCHEME="Larceny"
    # - SCHEME="Racket_6.2"
    # - SCHEME="Racket_HEAD"
    # - SCHEME="SagittariusScheme"
    # - SCHEME="VicareScheme"

matrix:
  fast_finish: true

addons:
  apt:
    packages:
      # For Vicare and GNU Guile
      - libgmp-dev
#       # Sagittarius
#       - libgc-dev
#       - zlib1g-dev
#       - libffi-dev
#       # For Larceny
#       - libc6:i386
      # GNU Guile
      - libunistring-dev
      - gcc-4.8
    sources:
      - ubuntu-toolchain-r-test

language: c

cache:
  ccache: true
  directories:
    - $HOME/opt

os:
  - linux

compiler:
  - gcc

before_script:
  # Install scheme-ci
  - wget https://github.com/weinholt/scheme-ci/archive/master.zip -O scheme-ci-master.zip
  - unzip scheme-ci-master.zip
  - eval "$(CC=gcc-4.8 INSTALL_TARGET=$HOME/opt scheme-ci-master/install-scheme.sh $SCHEME)"

script:
  - ./run-tests.sh
